baseURL = "https://theofficenetwork.netlify.app/"
languageCode = "en-us"
title = "The Office Network"
theme = "introduction"


[markup.goldmark.renderer]
    unsafe = true

 [[menu.main]]
     name    = "Home"
     url     = "/"
     weight = 10

 [[menu.main]]
     identifier = "networks"
     name    = "Community detection"
     url     = "/networks/"
     weight = 20

 [[menu.main]]
     identifier = "temporalpatterns"
     name    = "Temporal patterns"
     url     = "/temporalpatterns/"
     weight = 30

 [[menu.main]]
     identifier = "dialogues"
     name    = "Dialogues deep dive"
     url     = "/dialogues/"
     weight = 40

 [[menu.main]]
     identifier = "topic_modelling"
     name    = "Topic modelling"
     url     = "/topic_modelling/"
     weight = 50

[params]
    themeStyle                  = "light"
    fadeIn                  = false

# Configure the home page
[params.home]
    introHeight 		= "small"